fix(typescript): fix type errors in converted code (#5009)
* chore(typescript): enable type checks

* fix(codegen): update icon generation script

* fix(codegen): src/timezonepicker/update-tzdata.js

* chore(ts): disable ts checks for documentation site

* fix(typescript): manual fixes

* fix(typescript): override resize-observer-polyfill type definition

* fix(typescript): expose more component props

* fix(typescript): simplify types

this is needed to avoid possible, error:

"error TS2590: Expression produces a union type that is too complex to represent."

when using "styled" on typography components

* remove /index in imports

* fix: locale imports

* fix: avoid importing internals

* fix(typescript): fix types for banner component

* fix(typescript): fix types for badge component

* fix: remove file extensions(incorrect) in extract type imports

* fix: smaller generated types improve type

* fix: use updated StyletronComponent

* fix: component overrides for Block and related components

* fix: component overrides for Button component

* fix: icon types

* fix(ts): fixing type errors in tests

* chore(ts): enable type check for tests

* fix(ts): use react 17 type definitions

* fix(ts): fixing type errors in tests

* fix(ts): fixing type errors in tests

* fix: fix import paths in the tests

* fix(wip): types alignment

* fix: $as in button component

* fix(typescript): remove useless typecasts

* fix(typescript): improve types, more fixes

* fix(types): fix tabIndex to be a number

* fix(types): improve types for withStyles function

* fix(types): incorrect usage of React.MouseEvent instead of MouseEvent

* fix(types): review feedback, updating/fixing todo comments

* chore(comments): mark todos added as part of migration

* chore(types): remove flow lint comments

* chore(types): remove FlowFixMe comments

* fix(types): improve AnchorPropsT